# Site settings
title_left    : "❯❯ "
title_right   : "strings < /dev/random" # default: ""
description   : "r4um's blog."
keywords      : "blog, web, minimalist, thinkspace, systems, engineering, DevOps, SRE, linux, unix, networking, r4um, pranay, pranay kanwar, poetry, machine learning, statistics, probability"
url           : https://blog.r4um.net # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "https://avatars1.githubusercontent.com/u/629631?s=460&v=4" # image uri like logo/cover image for site seo

google_analytics  : UA-139122848-1
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/

markdown    : kramdown
kramdown:
  input: GFM

highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Pranay Kanwar"
  github   : "r4um"
  linkedin : "pranay-kanwar"
  keybase  : "r4um"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"

font-awesome:
  assets: true
